import { createEnv } from '@t3-oss/env-nextjs';
import { z } from 'zod';

export const env = createEnv({
  server: {
    DATABASE_URL: z.string().url(),
    NODE_ENV: z
      .enum(['development', 'test', 'production'])
      .default('development'),
    /** Required for `/admin`; optional so CI/Vercel can build without secrets. */
    SITE_ADMIN_PASSWORD: z.string().min(1).optional(),
    ADMIN_SESSION_SECRET: z.string().min(32).optional(),
    BEEHIIV_API_KEY: z.string().min(1).optional(),
    BEEHIIV_PUBLICATION_ID: z.string().min(1).optional(),
    BETTER_AUTH_SECRET: z.string().min(32).optional(),
    BETTER_AUTH_URL: z.string().url().optional(),
    RESEND_API_KEY: z.string().min(1).optional(),
    UPSTASH_REDIS_REST_URL: z.string().url().optional(),
    UPSTASH_REDIS_REST_TOKEN: z.string().min(1).optional(),
    BLOB_READ_WRITE_TOKEN: z.string().min(1).optional(),
    POLAR_ACCESS_TOKEN: z.string().min(1).optional(),
    POLAR_WEBHOOK_SECRET: z.string().min(1).optional(),
    POLAR_PRO_MONTHLY_PRODUCT_ID: z.string().min(1).optional(),
    POLAR_PRO_YEARLY_PRODUCT_ID: z.string().min(1).optional(),
    POLAR_BUSINESS_MONTHLY_PRODUCT_ID: z.string().min(1).optional(),
    POLAR_BUSINESS_YEARLY_PRODUCT_ID: z.string().min(1).optional(),
    POLAR_SERVER: z.enum(['sandbox', 'production']).optional(),
    AI_GATEWAY_API_KEY: z.string().min(1).optional(),
    GITHUB_CLIENT_ID: z.string().min(1).optional(),
    GITHUB_CLIENT_SECRET: z.string().min(1).optional(),
    GOOGLE_CLIENT_ID: z.string().min(1).optional(),
    GOOGLE_CLIENT_SECRET: z.string().min(1).optional(),
    VERCEL_PROJECT_ID: z.string().min(1).optional(),
    VERCEL_TEAM_ID: z.string().min(1).optional(),
    VERCEL_TOKEN: z.string().min(1).optional(),
  },
  client: {
    NEXT_PUBLIC_URL: z.string().optional(),
    NEXT_PUBLIC_SITE_URL: z.string().optional(),
  },
  runtimeEnv: {
    DATABASE_URL: process.env.DATABASE_URL,
    NODE_ENV: process.env.NODE_ENV,
    SITE_ADMIN_PASSWORD: process.env.SITE_ADMIN_PASSWORD,
    ADMIN_SESSION_SECRET: process.env.ADMIN_SESSION_SECRET,
    BEEHIIV_API_KEY: process.env.BEEHIIV_API_KEY,
    BEEHIIV_PUBLICATION_ID: process.env.BEEHIIV_PUBLICATION_ID,
    BETTER_AUTH_SECRET: process.env.BETTER_AUTH_SECRET,
    BETTER_AUTH_URL: process.env.BETTER_AUTH_URL,
    NEXT_PUBLIC_URL: process.env.NEXT_PUBLIC_URL,
    NEXT_PUBLIC_SITE_URL: process.env.NEXT_PUBLIC_SITE_URL,
    RESEND_API_KEY: process.env.RESEND_API_KEY,
    UPSTASH_REDIS_REST_URL: process.env.UPSTASH_REDIS_REST_URL,
    UPSTASH_REDIS_REST_TOKEN: process.env.UPSTASH_REDIS_REST_TOKEN,
    BLOB_READ_WRITE_TOKEN: process.env.BLOB_READ_WRITE_TOKEN,
    POLAR_ACCESS_TOKEN: process.env.POLAR_ACCESS_TOKEN,
    POLAR_WEBHOOK_SECRET: process.env.POLAR_WEBHOOK_SECRET,
    POLAR_PRO_MONTHLY_PRODUCT_ID: process.env.POLAR_PRO_MONTHLY_PRODUCT_ID,
    POLAR_PRO_YEARLY_PRODUCT_ID: process.env.POLAR_PRO_YEARLY_PRODUCT_ID,
    POLAR_BUSINESS_MONTHLY_PRODUCT_ID:
      process.env.POLAR_BUSINESS_MONTHLY_PRODUCT_ID,
    POLAR_BUSINESS_YEARLY_PRODUCT_ID:
      process.env.POLAR_BUSINESS_YEARLY_PRODUCT_ID,
    POLAR_SERVER: process.env.POLAR_SERVER,
    AI_GATEWAY_API_KEY: process.env.AI_GATEWAY_API_KEY,
    GITHUB_CLIENT_ID: process.env.GITHUB_CLIENT_ID,
    GITHUB_CLIENT_SECRET: process.env.GITHUB_CLIENT_SECRET,
    GOOGLE_CLIENT_ID: process.env.GOOGLE_CLIENT_ID,
    GOOGLE_CLIENT_SECRET: process.env.GOOGLE_CLIENT_SECRET,
    VERCEL_PROJECT_ID: process.env.VERCEL_PROJECT_ID,
    VERCEL_TEAM_ID: process.env.VERCEL_TEAM_ID,
    VERCEL_TOKEN: process.env.VERCEL_TOKEN,
  },
  skipValidation: !!process.env.SKIP_ENV_VALIDATION,
});
